version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: "all"
    cooldown:
      default-days: 3
    groups:
      test:
        patterns:
          - "climate_control"
          - "govuk_test"
          - "rack-test"
          - "rspec-*"
          - "simplecov"
          - "webmock"

  - package-ecosystem: github-actions
    directory: /
    cooldown:
      default-days: 3
    schedule:
      interval: daily
